name: Code Linting

on:
  workflow_dispatch:
  push:
    branches:
      - '**'
  pull_request:
    branches: [ main ]

jobs:
  cfn-lint:
    name: Run cfn-lint scan
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
          # Step 1: Check out the repository
          - name: Checkout repository
            uses: actions/checkout@v3

          # Step 2: Set up Python environment
          - name: Set up Python
            uses: actions/setup-python@v4
            with:
              python-version: '3.x'

          # Step 3: Install cfn-lint
          - name: Install cfn-lint
            run: |
              python -m pip install --upgrade pip
              pip install cfn-lint

          # Step 4: Run cfn-lint
          - name: Lint CloudFormation templates
            run: |
              cfn-lint cloudformation/**/*.yaml || cfn-lint cloudformation/**/*.yml

  cfn-nag:
    name: Run cfn-nag scan
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    needs: cfn-lint

    steps:
      - name: Clone repo
        uses: actions/checkout@v2

      - name: Run cfn-nag
        uses: stelligent/cfn_nag@master
        with:
          input_path: cloudformation

  pylint:
    name: Run Pylint on Python files
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # Step 3: Install Pylint
      - name: Install Pylint
        run: |
          python -m pip install --upgrade pip
          pip install pylint

      # Step 4: Run Pylint
      - name: Run Pylint on all Python files
        run: |
          # Run pylint on the root file
          pylint *.py || true
          # Run pylint on all Python files in the modules directory
          pylint modules/**/*.py || true
